/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_audiorecoder_AudioEncoder */

#ifndef _Included_com_wind_ndk_audiorecoder_AudioEncoder
#define _Included_com_wind_ndk_audiorecoder_AudioEncoder
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_audiorecoder_AudioEncoder
 * Method:    encode
 * Signature: (Ljava/lang/String;IIILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_audio_recorder_AudioEncoder_encode
  (JNIEnv *, jobject, jstring, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
